"use client";

import { useState, useEffect } from "react";
import RenderProgress from "../components/RenderProgress";
import { escape } from "node:querystring";

type RenderStatus =
  | "idle"
  | "queued"
  | "rendering"
  | "assembling"
  | "complete"
  | "error";
type RenderMode = "full" | "image" | "video" | "audio";

interface HistoryItem {
  id: string;
  url: string;
  thumbnail: string;
  createdAt: string;
  size: string;
}

export default function Page() {
  const [activeMode, setActiveMode] = useState<RenderMode>("full");
  const [script, setScript] = useState("");
  const [jobId, setJobId] = useState<string | null>(null);
  const [status, setStatus] = useState<RenderStatus>("idle");
  const [scenes, setScenes] = useState<any[]>([]);
  const [style, setStyle] = useState("cinematic");
  const [usage, setUsage] = useState(0);
  const [loading, setLoading] = useState(false);
  const [videoTitle, setVideoTitle] = useState("New AI Story");
  const [currentJobId, setCurrentJobId] = useState<string | null>(null);
  const [history, setHistory] = useState<HistoryItem[]>([]);
  const [isDeleting, setIsDeleting] = useState<string | null>(null);
  const [storageStats, setStorageStats] = useState({
    sizeMB: 0,
    formatted: "0 MB",
  });

  const fetchHistory = async () => {
    try {
      const res = await fetch("http://localhost:3001/api/history");
      if (res.ok) {
        const data = await res.json();
        setHistory(data);
      }
    } catch (err) {
      console.error("Failed to fetch history", err);
    }
  };
  useEffect(() => {
    fetchHistory();
  }, [status]);

  const resetState = () => {
    setJobId(null);
    setCurrentJobId(null);
    setStatus("idle");
    setScenes([]);
  };

  useEffect(() => {
    if (!jobId) return;
    const interval = setInterval(async () => {
      try {
        const res = await fetch(`http://localhost:3001/render/${jobId}`);
        if (res.status === 404) {
          setStatus("error");
          clearInterval(interval);
          return;
        }
        const data = await res.json();
        setStatus(data.status);
        setScenes(data.scenes ?? []);
        if (data.status === "complete" || data.status === "error")
          clearInterval(interval);
      } catch (err) {
        console.warn("Polling error, retrying...");
      }
    }, 2000);
    return () => clearInterval(interval);
  }, [jobId]);

  async function renderVideo(mode: RenderMode = "full") {
    if (!script.trim()) return;
    setActiveMode(mode);
    setStatus("queued");
    setScenes([]);

    try {
      const res = await fetch("http://localhost:3001/render", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ script, style, mode }),
      });
      const data = await res.json();
      if (!data.jobId) {
        setStatus("error");
        return;
      }
      setJobId(data.jobId);
      setCurrentJobId(data.jobId);
      setStatus("rendering");

      const suggestedTitle = script.split("\n")[0].replace(/[#*]/g, "").trim();
      setVideoTitle(suggestedTitle.substring(0, 95) || "New AI Story");
    } catch (error) {
      console.error("Render initiation failed:", error);
      setStatus("error");
    }
  }

  const handleUpload = async () => {
    if (!window.confirm("Publish to YouTube?")) return;
    setLoading(true);
    try {
      const response = await fetch("http://localhost:3001/api/upload-youtube", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          jobId: currentJobId,
          title: videoTitle,
          description: "Generated by AI Video Studio",
        }),
      });
      const data = await response.json();
      if (data.success) {
        alert("🚀 Published!");
        window.open(`https://youtu.be/${data.videoId}`, "_blank");
      }
    } catch (err) {
      alert("Upload failed.");
    } finally {
      setLoading(false);
    }
  };
  const handleDelete = async (jobId: string) => {
    if (
      !window.confirm(
        "Are you sure you want to delete this video? This cannot be undone."
      )
    )
      return;
    setIsDeleting(jobId);
    try {
      const res = await fetch(`http://localhost:3001/api/history/${jobId}`, {
        method: "DELETE",
      });
      if (res.ok) {
        setHistory((prev) => prev.filter((item) => item.id !== jobId));
      } else {
        alert("Server couldn't delete the files.");
      }
    } catch (err) {
      alert("Delete failed.");
    } finally {
      setIsDeleting(null);
    }
  };
  // STORAGE STATS FETCH
  const fetchStorageStats = async () => {
    const res = await fetch("http://localhost:3001/api/storage-stats");
    if (res.ok) {
      const data = await res.json();
      setStorageStats(data);
    }
  };

  // Storage stats fetching oon server start or vid deletion
  useEffect(() => {
    fetchStorageStats();
  }, [history]);

  return (
    <main
      style={{
        padding: 40,
        maxWidth: 900,
        margin: "0 auto",
        fontFamily: "sans-serif",
      }}
    >
      <h1>AI Video Studio</h1>

      <textarea
        rows={10}
        style={{ width: "100%", marginTop: 16, padding: 12, borderRadius: 8 }}
        placeholder="Paste script here..."
        value={script}
        onChange={(e) => setScript(e.target.value)}
      />

      <select
        value={style}
        onChange={(e) => setStyle(e.target.value)}
        style={{ marginTop: 16, display: "block", padding: "8px" }}
      >
        <option value="cinematic">Cinematic</option>
        <option value="documentary">Documentary</option>
        <option value="animation">Animation</option>
        <option value="horror">News</option>
        <option value="bright">Fantasy</option>
        <option value="minimal">Minimal</option>
        <option value="anime_ghibli">Anime Ghibli</option>
        <option value="noir">Noir</option>
        <option value="cyberpunk">Cyberpunk</option>
        <option value="fine_art">Fine Art</option>
      </select>

      <div style={{ marginTop: 24, display: "flex", gap: 12 }}>
        <button
          onClick={() => renderVideo("full")}
          disabled={status === "rendering" || status === "assembling"}
          style={{
            padding: "12px 24px",
            fontWeight: "bold",
            cursor: "pointer",
          }}
        >
          {status === "rendering" || status === "assembling"
            ? "🎬 Rendering..."
            : "🎬 One-Click Render"}
        </button>

        {(status === "complete" || status === "error") && (
          <button onClick={resetState} style={{ padding: "12px 24px" }}>
            🔄 New Project
          </button>
        )}
      </div>

      {/*ADVANCED OPTIONS */}
      <details style={{ marginTop: 16 }} open={status === "idle"}>
        <summary style={{ cursor: "pointer" }}>Advanced options</summary>
        <div style={{ display: "flex", gap: 12, marginTop: 12 }}>
          <button
            disabled={status !== "idle"}
            onClick={() => renderVideo("image")}
          >
            🖼 Image only
          </button>
          {/* <button
            disabled={status !== "idle"}
            onClick={() => renderVideo("video")}
          >
            🎥 Video only
          </button> */}
          <button
            disabled={status !== "idle"}
            onClick={() => renderVideo("audio")}
          >
            🎙 Audio only
          </button>
        </div>
      </details>

      <hr style={{ margin: "40px 0", opacity: 0.2 }} />

      <RenderProgress
        status={status}
        scene={scenes.filter((s) => s.status === "complete").length}
        total={scenes.length}
      />

      {status === "complete" && (
        <div style={{ marginTop: 32 }}>
          <h3>Final Result:</h3>
          {/* VIDEO VIEW */}
          {(activeMode === "full" || activeMode === "video") && (
            <div key={jobId}>
              <video style={{ width: "100%", borderRadius: 8 }} controls>
                <source
                  src={`http://localhost:3001/media/output/final_${jobId}.mp4?t=${Date.now()}`}
                  type="video/mp4"
                />
              </video>
              {/* Render your YouTube Publish box here only for video modes */}
            </div>
          )}

          {/* AUDIO VIEW */}
          {activeMode === "audio" && (
            <div
              style={{
                padding: 20,
                background: "#f0f0f0",
                borderRadius: 8,
              }}
            >
              <audio controls style={{ width: "100%" }}>
                <source
                  src={`http://localhost:3001/media/output/final_${jobId}.mp3?t=${Date.now()}`}
                  type="audio/mpeg"
                />
              </audio>
              <p style={{ textAlign: "center", marginTop: 10 }}>
                🎙 Narration Audio Generated
              </p>
            </div>
          )}

          {/* IMAGE VIEW */}
          {activeMode === "image" && (
            <div style={{ marginTop: 20 }}>
              <div
                style={{
                  display: "grid",
                  gridTemplateColumns: "repeat(auto-fill, minmax(200px, 1fr))",
                  gap: 16,
                }}
              >
                {scenes.map((scene, idx) => {
                  const imgUrl = `http://localhost:3001/media/images/scene_${idx}_${jobId}.png?t=${Date.now()}`;
                  return (
                    <div
                      key={idx}
                      style={{
                        border: "1px solid #eee",
                        padding: 8,
                        borderRadius: 8,
                        background: "#fff",
                      }}
                    >
                      <img
                        src={imgUrl}
                        style={{
                          width: "100%",
                          borderRadius: 4,
                          aspectRatio: "16/9",
                          objectFit: "cover",
                        }}
                        alt={`Scene ${idx}`}
                      />
                      <div
                        style={{
                          marginTop: 8,
                          display: "flex",
                          justifyContent: "space-between",
                          alignItems: "center",
                        }}
                      >
                        <span style={{ fontSize: 12, color: "#666" }}>
                          Scene {idx}
                        </span>
                        <a
                          href={imgUrl}
                          download={`scene_${idx}.png`}
                          style={{ textDecoration: "none" }}
                        >
                          <button
                            style={{
                              padding: "4px 8px",
                              fontSize: 11,
                              cursor: "pointer",
                              background: "#eee",
                              border: "none",
                              borderRadius: 4,
                            }}
                          >
                            ⬇️ Save
                          </button>
                        </a>
                      </div>
                    </div>
                  );
                })}
              </div>
            </div>
          )}
          <div
            style={{
              background: "#f9f9f9",
              padding: 16,
              borderRadius: 8,
              marginTop: 16,
            }}
          >
            <label style={{ fontSize: 12, fontWeight: "bold" }}>
              YouTube Title
            </label>
            <input
              type="text"
              value={videoTitle}
              onChange={(e) => setVideoTitle(e.target.value)}
              style={{
                width: "100%",
                padding: 8,
                margin: "8px 0 16px 0",
                borderRadius: 4,
                border: "1px solid #ccc",
              }}
            />

            <div style={{ display: "flex", gap: 12, alignItems: "center" }}>
              <a
                href={`http://localhost:3001/media/output/final_${jobId}.mp4?t=${Date.now()}`}
                download
                style={{ textDecoration: "none" }}
              >
                <button
                  style={{ height: 36, padding: "0 16px", cursor: "pointer" }}
                >
                  ⬇️ Download MP4
                </button>
              </a>
              {/* {activeMode === "image" && (
            <button
              onClick={() => {
                scenes.forEach((_, idx) => {
                  const link = document.createElement("a");
                  link.href = `http://localhost:3001/media/images/scene_${idx}_${jobId}.png`;
                  link.download = `scene_${idx}.png`;
                  link.click();
                });
              }}
              style={{
                marginBottom: 16,
                padding: "8px 16px",
                cursor: "pointer",
              }}
            >
              📥 Download All Scenes
            </button>
          )} */}

              <button
                onClick={handleUpload}
                disabled={loading || !currentJobId}
                style={{
                  height: 36,
                  padding: "0 20px",
                  borderRadius: 4,
                  background: loading || !currentJobId ? "#ccc" : "#FF0000",
                  color: "white",
                  fontWeight: "bold",
                  border: "none",
                  cursor: loading || !currentJobId ? "not-allowed" : "pointer",
                }}
              >
                {loading ? "Uploading..." : "🚀 Publish to YouTube"}
              </button>
            </div>
          </div>
        </div>
      )}
      <hr
        style={{ margin: "60px 0", border: "0", borderTop: "1px solid #eee" }}
      />
      {/* 📊 STORAGE MONITORING INNIT */}
      <div
        style={{
          background: "#f0f2f5",
          padding: "15px 20px",
          borderRadius: "12px",
          marginBottom: "30px",
          display: "flex",
          alignItems: "center",
          justifyContent: "space-between",
          border: "1px solid #e1e4e8",
        }}
      >
        <div>
          <h4 style={{ margin: 0, color: "#444" }}>Disk Usage</h4>
          <p style={{ margin: "4px 0 0 0", fontSize: "14px", color: "#666" }}>
            Your current media library is using{" "}
            <strong>{storageStats.formatted}</strong>
          </p>
        </div>

        <div style={{ width: "200px" }}>
          <div
            style={{
              height: "8px",
              width: "100%",
              background: "#ddd",
              borderRadius: "4px",
              overflow: "hidden",
            }}
          >
            <div
              style={{
                height: "100%",
                width: `${Math.min((storageStats.sizeMB / 2000) * 100, 100)}%`,
                background: storageStats.sizeMB > 1500 ? "#ff4d4f" : "#52c41a",
              }}
            />
          </div>
          <p
            style={{
              fontSize: "11px",
              textAlign: "right",
              marginTop: "4px",
              color: "#999",
            }}
          >
            Target Limit: 2 GB
          </p>
        </div>
      </div>
      {/* 🎬 HISTORY YY */}
      <section>
        <div
          style={{
            display: "flex",
            justifyContent: "space-between",
            alignItems: "center",
          }}
        >
          <h2>🎥 Production History</h2>
          <button
            onClick={fetchHistory}
            style={{
              background: "none",
              border: "1px solid #ccc",
              borderRadius: 4,
              cursor: "pointer",
              padding: "4px 8px",
            }}
          >
            Refresh
          </button>
        </div>

        <div
          style={{
            display: "grid",
            gridTemplateColumns: "repeat(auto-fill, minmax(250px, 1fr))",
            gap: 20,
            marginTop: 20,
          }}
        >
          {history.length === 0 && (
            <p style={{ color: "#888" }}>No videos found in library.</p>
          )}

          {history.map((video) => (
            <div
              key={video.id}
              style={{
                background: "#fff",
                borderRadius: 12,
                overflow: "hidden",
                boxShadow: "0 4px 12px rgba(0,0,0,0.1)",
                display: "flex",
                flexDirection: "column",
              }}
            >
              {/* Thumbnail Preview */}
              <div
                style={{
                  width: "100%",
                  aspectRatio: "16/9",
                  background: "#222",
                  position: "relative",
                  display: "flex",
                  alignItems: "center",
                  justifyContent: "center",
                }}
              >
                <img
                  src={`http://localhost:3001${video.thumbnail}`}
                  alt="Preview"
                  style={{
                    width: "100%",
                    height: "100%",
                    objectFit: "cover",
                    position: "absolute",
                    zIndex: 2,
                  }}
                  onError={(e) => {
                    // Hide the broken image icon
                    e.currentTarget.style.display = "none";
                  }}
                />
                {/* This text/icon shows if the image above fails or is hidden */}
                <span
                  style={{
                    color: "#555",
                    fontSize: "12px",
                    fontWeight: "bold",
                  }}
                >
                  🎬 NO PREVIEW
                </span>
              </div>

              <div style={{ padding: 15 }}>
                <p
                  style={{
                    fontWeight: "bold",
                    fontSize: "14px",
                    margin: "0 0 4px 0",
                    color: "#333",
                  }}
                >
                  Project {video.id.substring(0, 8)}
                </p>
                <p
                  style={{
                    fontSize: "11px",
                    color: "#888",
                    margin: "0 0 10px 0",
                  }}
                >
                  {new Date(video.createdAt).toLocaleString()} • {video.size}
                </p>

                <div style={{ display: "flex", gap: 10 }}>
                  <a
                    href={`http://localhost:3001${video.url}`}
                    target="_blank"
                    style={{
                      flex: 1,
                      textAlign: "center",
                      background: "#f0f0f0",
                      color: "#333",
                      padding: "8px",
                      borderRadius: 6,
                      textDecoration: "none",
                      fontSize: "13px",
                    }}
                  >
                    Watch
                  </a>
                  <a
                    href={`http://localhost:3001${video.url}?download=true`}
                    download
                    style={{
                      flex: 1,
                      textAlign: "center",
                      background: "#007bff",
                      color: "#fff",
                      padding: "8px",
                      borderRadius: 6,
                      textDecoration: "none",
                      fontSize: "13px",
                    }}
                  >
                    Download
                  </a>
                  <button
                    onClick={() => handleDelete(video.id)}
                    style={{
                      background: "#fff",
                      color: "#ff4d4f",
                      border: "1px solid #ff4d4f",
                      padding: "8px",
                      borderRadius: 6,
                      cursor: "pointer",
                      fontSize: "13px",
                      flex: 0.5,
                    }}
                  >
                    🗑️
                  </button>
                </div>
              </div>
            </div>
          ))}
        </div>
      </section>
    </main>
  );
}
const styles = {
  container: {
    marginTop: "50px",
    borderTop: "1px solid #ddd",
    paddingTop: "30px",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "20px",
  },
  refreshBtn: {
    padding: "8px 16px",
    borderRadius: "6px",
    border: "1px solid #ccc",
    cursor: "pointer",
    background: "#fff",
  },
  grid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(280px, 1fr))",
    gap: "20px",
  },
  card: {
    background: "#fff",
    borderRadius: "10px",
    overflow: "hidden",
    boxShadow: "0 4px 12px rgba(0,0,0,0.08)",
    transition: "transform 0.2s",
  },
  thumbContainer: {
    position: "relative",
    width: "100%",
    height: "157px",
    background: "#000",
  },
  image: { width: "100%", height: "100%", objectFit: "cover" },
  badge: {
    position: "absolute",
    top: "10px",
    right: "10px",
    background: "rgba(0,0,0,0.6)",
    color: "#fff",
    padding: "2px 8px",
    borderRadius: "4px",
    fontSize: "10px",
  },
  details: { padding: "15px" },
  jobId: { margin: "0 0 4px 0", fontSize: "14px", fontWeight: "bold" },
  date: { margin: "0 0 15px 0", fontSize: "12px", color: "#888" },
  btnGroup: { display: "flex", gap: "10px" },
  viewBtn: {
    flex: 1,
    textAlign: "center",
    padding: "10px",
    background: "#000",
    color: "#fff",
    textDecoration: "none",
    borderRadius: "6px",
    fontSize: "13px",
  },
  downloadBtn: {
    flex: 1,
    textAlign: "center",
    padding: "10px",
    border: "1px solid #000",
    color: "#000",
    textDecoration: "none",
    borderRadius: "6px",
    fontSize: "13px",
  },
};
